<link rel="stylesheet" href="{{asset('/templates/visiteurs/assets/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('/templates/visiteurs/assets/css/owl.carousel.min.css')}}">
<link rel="stylesheet" href="{{asset('/templates/visiteurs/assets/css/flaticon.css')}}">
<link rel="stylesheet" href="{{asset('/templates/visiteurs/assets/css/price_rangs.css')}}">
<link rel="stylesheet" href="{{asset('/templates/visiteurs/assets/css/slicknav.css')}}">
<link rel="stylesheet" href="{{asset('/templates/visiteurs/assets/css/animate.min.css')}}">
<link rel="stylesheet" href="{{asset('/templates/visiteurs/assets/css/magnific-popup.css')}}">
<link rel="stylesheet" href="{{asset('/templates/visiteurs/assets/css/fontawesome-all.min.css')}}">
<link rel="stylesheet" href="{{asset('/templates/visiteurs/assets/css/themify-icons.css')}}">
<link rel="stylesheet" href="{{asset('/templates/visiteurs/assets/css/slick.css')}}">
<link rel="stylesheet" href="{{asset('/templates/visiteurs/assets/css/nice-select.css')}}">
<link rel="stylesheet" href="{{asset('/templates/visiteurs/assets/css/style.css')}}">
